# Generated by Django 2.0.6 on 2018-06-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180625_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_done',
            new_name='finished_date',
        ),
    ]
