# Generated by Django 2.0.6 on 2018-06-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180625_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='finished_date',
        ),
    ]
