# Generated by Django 2.0.6 on 2018-06-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
