# Generated by Django 2.0.6 on 2018-06-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
